version: '3.7'
services:
  jenkins:
#    image: jenkins/jenkins:lts
    build: .
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - D:/TaoLuan/DEV_WORKSPACE/learning/jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock